export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const RETAKE_EXAM = 'RETAKE_EXAM';
export const GRADE_EXAM = 'GRADE_EXAM';
export const EDIT_QUESTION = 'EDIT_QUESTION';